version: '3.7'
services:
  mysql:
    build: ./sql
    hostname: 'mysql'
    container_name: shorty-db
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_NAME}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
  api:
    build:
      context: ./server
      args:
        - NODE_ENV=${NODE_ENV}
        - SERVER_HOST=${SERVER_HOST}
        - SERVER_PORT=${SERVER_PORT}
        - DOMAIN=${DOMAIN}
        - SENTRY_URL_SHORTENER_SERVER_DNS=${SENTRY_URL_SHORTENER_SERVER_DNS}
        - DB_URL=${DB_URL}
        - DB_PORT=${DB_PORT}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
        - DB_CONNECTION_LIMIT=${DB_CONNECTION_LIMIT}
        - JWT_SECRET=${JWT_SECRET}
        - JWT_EXPIRE_IN=${JWT_EXPIRE_IN}
        - JWT_ISSUER=${JWT_ISSUER}
        - RWT_SECRET=${RWT_SECRET}
        - RWT_EXPIRE_IN=${RWT_EXPIRE_IN}
    hostname: 'api'
    container_name: shorty-api
    restart: unless-stopped
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - WAIT_HOSTS=mysql:${DB_PORT}
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    volumes:
      - ./server:/usr/src/server
      - ./sql:/usr/src/sql
      - /usr/src/server/node_modules
  proxy:
    build:
      context: ./proxy
      args:
        - NODE_ENV=${NODE_ENV}
        - PROXY_HOST=${PROXY_HOST}
        - PROXY_PORT=${PROXY_PORT}
        - DOMAIN=${DOMAIN}
        - SENTRY_URL_SHORTENER_PROXY_DNS=${SENTRY_URL_SHORTENER_PROXY_DNS}
        - DB_URL=${DB_URL}
        - DB_PORT=${DB_PORT}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
        - DB_CONNECTION_LIMIT=${DB_CONNECTION_LIMIT}
    hostname: 'proxy'
    container_name: shorty-proxy
    restart: unless-stopped
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - WAIT_HOSTS=mysql:${DB_PORT}
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    volumes:
      - ./proxy:/usr/src/proxy
      - ./sql:/usr/src/sql
      - /usr/src/proxy/node_modules
    ports:
      - ${PROXY_PORT}:${PROXY_PORT}
  client:
    tty: true
    build:
      context: ./client
      args:
        - NODE_ENV=${NODE_ENV}
        - CLIENT_PORT=${CLIENT_PORT}
        - SERVER_HOST=${SERVER_HOST}
        - SERVER_PORT=${SERVER_PORT}
        - HTTP_SCHEME=${HTTP_SCHEME}
        - DOMAIN=${DOMAIN}
        - SENTRY_URL_SHORTENER_CLIENT_DNS=${SENTRY_URL_SHORTENER_CLIENT_DNS}
    hostname: 'client'
    container_name: shorty-client
    restart: unless-stopped
    links:
      - proxy
      - api
    depends_on:
      - proxy
      - api
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
  mailcatcher:
    image: yappabe/mailcatcher
    hostname: 'mailcatcher'
    container_name: shorty-mailcatcher
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '1080:1080'
volumes:
  db-data:
    driver: local
networks:
  ipam:
    driver: default
